- env-var: ["MANPATH", "/usr/local/opt/libpq/share/man:$MANPATH"]
- env-var: ["MANPATH", "/usr/local/opt/mysql-client/share/man:$MANPATH"]
- env-var: ["MANPATH", "/usr/local/opt/openjdk/share/man:$MANPATH"]
