- brew-formula: ["binutils"]
- brew-formula: ["findutils"]
- brew-formula: ["gawk"]
- brew-formula: ["gnu-getopt"]
- brew-formula: ["gnu-indent"]
- brew-formula: ["gnu-sed"]
- brew-formula: ["gnu-tar"]
- brew-formula: ["gnutls"]
- brew-formula: ["inetutils"]
- brew-formula: ["make"]
- brew-formula: ["moreutils"]

- brew-formula: ["diff-so-fancy"]
- brew-formula: ["duf"]
- brew-formula: ["duti"]
- brew-formula: ["fd"]
- brew-formula: ["ffmpeg"]
- brew-formula: ["fzf"]
- brew-formula: ["gh"]
- brew-formula: ["gnupg"]
- brew-formula: ["graphviz"]
- brew-formula: ["grip"]
- brew-formula: ["htop"]
- brew-formula: ["httpie"]
- brew-formula: ["imagemagick"]
- brew-formula: ["jq"]
- brew-formula: ["librsvg"]
- brew-formula: ["mas"]
- brew-formula: ["ncdu"]
- brew-formula: ["nload"]
- brew-formula: ["p7zip"]
- brew-formula: ["pandoc"]
- brew-formula: ["pipx"]
- brew-formula: ["ripgrep"]
- brew-formula: ["shadowsocks-rust"]
- brew-formula: ["speedtest-cli"]
- brew-formula: ["tree"]
- brew-formula: ["v2ray"]
- brew-formula: ["websocat"]
- brew-formula: ["wget"]
- brew-formula: ["wireguard-tools"]
- brew-formula: ["youtube-dl"]

- brew-formula: ["gcc"]
- brew-formula: ["lua"]
- brew-formula: ["node"]
- brew-formula: ["openjdk"]
- brew-formula: ["rust"]

- brew-formula: ["ansible"]
- brew-formula: ["clang-format"]
- brew-formula: ["golang-migrate"]
- brew-formula: ["google-java-format"]
- brew-formula: ["libpq"]
- brew-formula: ["mongodb/brew/mongodb-database-tools"]
- brew-formula: ["mysql-client"]
- brew-formula: ["poetry"]
- brew-formula: ["stylua"]
- brew-formula: ["yarn"]

- brew-formula: ["binwalk"]
- brew-formula: ["bulk_extractor"]
- brew-formula: ["exiftool"]
- brew-formula: ["fcrackzip"]
- brew-formula: ["gobuster"]
- brew-formula: ["hydra"]
- brew-formula: ["john-jumbo"]
- brew-formula: ["masscan"]
- brew-formula: ["massdns"]
- brew-formula: ["mitmproxy"]
- brew-formula: ["nmap"]
- brew-formula: ["owasp-amass/amass/amass"]
- brew-formula: ["rustscan"]
- brew-formula: ["sleuthkit"]
- brew-formula: ["sqlmap"]
- brew-formula: ["sslsplit"]
- brew-formula: ["subfinder"]
- brew-formula: ["virustotal-cli"]
- brew-formula: ["volatility"]
- brew-formula: ["yara"]

- brew-cask: ["alfred"]
- brew-cask: ["appcleaner"]
- brew-cask: ["discord"]
- brew-cask: ["docker"]
- brew-cask: ["figma"]
- brew-cask: ["firefox"]
- brew-cask: ["font-xits"]
- brew-cask: ["gimp"]
- brew-cask: ["google-chrome"]
- brew-cask: ["imhex"]
- brew-cask: ["mactex-no-gui"]
- brew-cask: ["ngrok"]
- brew-cask: ["notion"]
- brew-cask: ["openvpn-connect"]
- brew-cask: ["postman"]
- brew-cask: ["rar"]
- brew-cask: ["shadowsocksx-ng"]
- brew-cask: ["spotify"]
- brew-cask: ["tor-browser"]
- brew-cask: ["tunnelblick"]
- brew-cask: ["visual-studio-code"]
- brew-cask: ["vlc"]
- brew-cask: ["vmware-fusion"]
- brew-cask: ["wireshark"]

- mas: ["1352778147"] # Bitwarden
- mas: ["1487937127"] # Craft
- mas: ["1356178125"] # Outline
- mas: ["904280696"]  # Things
- mas: ["1451685025"] # WireGuard
