#/bin/sh

module="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

cat << EOF >> Brewfile
brew "binutils"
brew "findutils"
brew "gawk"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnutls"
brew "inetutils"
brew "make"
brew "moreutils"

brew "diff-so-fancy"
brew "duf"
brew "duti"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "gnupg"
brew "graphviz"
brew "grip"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "librsvg"
brew "mas"
brew "ncdu"
brew "nload"
brew "p7zip"
brew "pandoc"
brew "pipx"
brew "ripgrep"
brew "shadowsocks-rust"
brew "speedtest-cli"
brew "tree"
brew "v2ray"
brew "websocat"
brew "wget"
brew "wireguard-tools"
brew "youtube-dl"

brew "gcc"
brew "lua"
brew "node"
brew "openjdk"
brew "rust"

brew "ansible"
brew "clang-format"
brew "golang-migrate"
brew "google-java-format"
brew "libpq"
brew "mongodb/brew/mongodb-database-tools"
brew "mysql-client"
brew "poetry"
brew "stylua"
brew "yarn"

brew "binwalk"
brew "bulk_extractor"
brew "exiftool"
brew "fcrackzip"
brew "gobuster"
brew "hydra"
brew "john-jumbo"
brew "masscan"
brew "massdns"
brew "mitmproxy"
brew "nmap"
brew "owasp-amass/amass/amass"
brew "rustscan"
brew "sleuthkit"
brew "sqlmap"
brew "sslsplit"
brew "subfinder"
brew "virustotal-cli"
brew "volatility"
brew "yara"

cask "alfred"
cask "appcleaner"
cask "discord"
cask "docker"
cask "figma"
cask "firefox"
cask "font-xits"
cask "gimp"
cask "google-chrome"
cask "imhex"
cask "mactex-no-gui"
cask "ngrok"
cask "notion"
cask "openvpn-connect"
cask "postman"
cask "rar"
cask "shadowsocksx-ng"
cask "spotify"
cask "tor-browser"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "wireshark"

mas "Bitwarden", id: 1352778147
mas "Craft", id: 1487937127
mas "Outline", id: 1356178125
mas "Things", id: 904280696 
mas "WireGuard", id: 1451685025
EOF
