BrewFormula = [
  ["binutils"],                            # section 1
  ["findutils"],
  ["gawk"],
  ["gnu-getopt"],
  ["gnu-indent"],
  ["gnu-sed"],
  ["gnu-tar"],
  ["gnutls"],
  ["inetutils"],
  ["make"],
  ["moreutils"],
  ["diff-so-fancy"],                       # section 2
  ["duf"],
  ["duti"],
  ["fd"],
  ["ffmpeg"],
  ["fzf"],
  ["gh"],
  ["gnupg"],
  ["graphviz"],
  ["grip"],
  ["htop"],
  ["httpie"],
  ["imagemagick"],
  ["jq"],
  ["librsvg"],
  ["mas"],
  ["ncdu"],
  ["nload"],
  ["p7zip"],
  ["pandoc"],
  ["pipx"],
  ["ripgrep"],
  ["shadowsocks-rust"],
  ["speedtest-cli"],
  ["tree"],
  ["v2ray"],
  ["websocat"],
  ["wget"],
  ["wireguard-tools"],
  ["youtube-dl"],
  ["gcc"],                                 # section 3
  ["lua"],
  ["node"],
  ["openjdk"],
  ["rust"],
  ["ansible"],                             # section 4
  ["clang-format"],
  ["golang-migrate"],
  ["google-java-format"],
  ["libpq"],
  ["mongodb/brew/mongodb-database-tools"],
  ["mysql-client"],
  ["poetry"],
  ["stylua"],
  ["yarn"],
  ["binwalk"],                             # section 5
  ["bulk_extractor"],
  ["exiftool"],
  ["fcrackzip"],
  ["gobuster"],
  ["hydra"],
  ["john-jumbo"],
  ["masscan"],
  ["massdns"],
  ["mitmproxy"],
  ["nmap"],
  ["owasp-amass/amass/amass"],
  ["rustscan"],
  ["sleuthkit"],
  ["sqlmap"],
  ["sslsplit"],
  ["subfinder"],
  ["virustotal-cli"],
  ["volatility"],
  ["yara"],
]

BrewCask = [
  ["alfred"],
  ["appcleaner"],
  ["discord"],
  ["docker"],
  ["figma"],
  ["firefox"],
  ["font-xits"],
  ["gimp"],
  ["google-chrome"],
  ["imhex"],
  ["mactex-no-gui"],
  ["ngrok"],
  ["notion"],
  ["openvpn-connect"],
  ["postman"],
  ["rar"],
  ["shadowsocksx-ng"],
  ["spotify"],
  ["tor-browser"],
  ["tunnelblick"],
  ["visual-studio-code"],
  ["vlc"],
  ["vmware-fusion"],
  ["wireshark"],
]

Mas = [
  ["1352778147"], # Bitwarden
  ["1487937127"], # Craft
  ["1356178125"], # Outline
  ["904280696"],  # Things
  ["1451685025"], # WireGuard
]
