Env = [
  ["LESS_TERMCAP_mb", "\u001b[1;31m"],
  ["LESS_TERMCAP_md", "\u001b[1;36m"],
  ["LESS_TERMCAP_me", "\u001b[0m"],
  ["LESS_TERMCAP_so", "\u001b[01;44;33m"],
  ["LESS_TERMCAP_se", "\u001b[0m"],
  ["LESS_TERMCAP_us", "\u001b[1;32m"],
  ["LESS_TERMCAP_ue", "\u001b[0m"],
  ["LESS", "-g -i -M -R -S -x4 --mouse --wheel-lines=5"],
]

BrewFormula = [
  ["less"],
]
