export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:$HOME/.local/dist/nvim/bin" # make-nvim
export PATH="$PATH:/opt/homebrew/opt/git/bin" # brew install git
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH" # brew install libpq
export PATH="/opt/homebrew/sbin:$PATH"

alias cdf='cd "$(finder-pwd)"' # finder-pwd is user-defined
alias dcb="docker compose build"
alias dcd="docker compose down"
alias dcdv="docker compose down -v"
alias dce="docker compose exec"
alias dcl="docker compose logs"
alias dclf="docker compose logs -f"
alias dcp="docker compose ps"
alias dcpa="docker compose ps -a"
alias dcr="docker compose run"
alias dcrr="docker compose run --rm"
alias dcu="docker compose up"
alias dcud="docker compose up -d"
alias ga="git add"
alias gap="git add --patch"
alias gb="git branch"
alias gc="git-commit--issue" # git-commit--issue is user-defined
alias gca="git commit --amend"
alias gcf="git commit --fixup"
alias gci='git commit --allow-empty -m "Initial commit"'
alias gco="git checkout"
alias gcp="git cherry-pick"
alias gcu='git reset --soft HEAD~1' # [U]ndo the last [c]ommit
alias gcw='git commit -m "wip"'
alias gd="git diff"
alias gdfm='git fetch && gdf $(git merge-base HEAD origin/master) origin/master'
alias gdq="git--quiet diff" # git--quiet is user-defined
alias gds="git diff --staged"
alias gdsq="git--quiet diff --staged" # git--quiet is user-defined
alias gf="git fetch"
alias gl="git --no-pager log --graph --oneline -n 20"
alias glp="git log --patch -n 1"
alias glpq="git--quiet log --patch -n 1" # git--quiet is user-defined
alias gls="git log -S"
alias gp="git push"
alias gr="git reset HEAD"
alias grb="git rebase"
alias grba="git rebase --autosquash"
alias grbai="git rebase --autosquash -i"
alias grbi="git rebase -i"
alias grc="git rebase --continue"
alias gs="git status -sb"
alias gso="git show"
alias gt="gotestsum -- --count 1 --tags integration --race"
alias gta="gotestsum -- --count 1 --tags integration --race ./..."
alias gtac="gotestsum -- ./..."
alias gu="git pull"
alias gum="git fetch --all && git rebase origin/master"
alias l="ls -1A"
alias ll="ls -lhFA"
alias sudo="sudo " # enables sudo for aliases
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

function bat() { command bat --paging=never "$@" }
function grep() { command grep --color=auto "$@" }
function ls() { command ls --color=auto "$@" }

for f in "$HOME"/.local/share/zsh/integration/*.zsh(N); do
	source "$f"
done
