Default = [
  ["com.apple.finder", "FXDefaultSearchScope", "SCcf"],          # search the current folder when performing a search
  ["com.apple.finder", "FXEnableExtensionChangeWarning", false], # don't show warning before changing an extension
  ["com.apple.finder", "FXPreferredViewStyle", "Nlsv"],          # use list view in all Finder windows
  ["com.apple.finder", "NewWindowTarget", "PfHm"],               # show home for new Finder windows
  ["com.apple.finder", "NewWindowTargetPath", "file://$HOME/"],  # show home for new Finder windows
  ["com.apple.finder", "ShowExternalHardDrivesOnDesktop", true], # show external disks on the desktop
  ["com.apple.finder", "ShowHardDrivesOnDesktop", false],        # don't show hard drives on the desktop
  ["com.apple.finder", "ShowMountedServersOnDesktop", false],    # don't show connected servers on the desktop
  ["com.apple.finder", "ShowRemovableMediaOnDesktop", true],     # show removable media on the desktop
  ["com.apple.finder", "_FXSortFoldersFirst", true],             # keep folders on top when sorting by name
]

Run = [
  ['/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" "$HOME/Library/Preferences/com.apple.finder.plist"'],  # snap-to-grid for icons on the desktop
  ['/usr/libexec/PlistBuddy -c "Set :ICloudViewSettings:IconViewSettings:arrangeBy grid" "$HOME/Library/Preferences/com.apple.finder.plist"'],   # snap-to-grid for icons in iCloud Drive
  ['/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" "$HOME/Library/Preferences/com.apple.finder.plist"'], # snap-to-grid for icons in other icon views
]
