#!/usr/bin/env zsh

set -e -o pipefail -u

function main() {
	local module_path

	for module_path in "$@"; do
		do_module "$module_path"
	done
}

function do_module() {
	local module_path="$1"

	[[ ! -e "$module_path" ]] && return 0

	do_module_bin "$module_path" || echo "error" >&2
	do_module_config "$module_path" || echo "error" >&2
	do_module_brewfile "$module_path" || echo "error" >&2
}

function do_module_bin() {
	local bin_path="$1/.bin"

	[[ ! -e "$bin_path" ]] && return 0

	for bin_entry_path in "$1/.bin/"*; do
		symlink "$(get_bin_path)/$(basename "$bin_entry_path")" "$bin_entry_path"
	done
}

function do_module_config() {
	local module_path="$1"
	local config_path="$module_path/.config"

	[[ ! -e "$config_path" ]] && return 0

	symlink "$(get_config_path)/$(basename "$module_path")" "$config_path"
}

function do_module_brewfile() {
	local module_path="$1"
	local brewfile_path="$module_path/.brewfile"

	[[ ! -e "$brewfile_path" ]] && return 0

	brewfile "$brewfile_path"
}

function get_bin_path() {
	printf "%s" "$HOME/.local/bin"
}

function get_config_path() {
	printf "%s" "$HOME/.config"
}

function symlink() {
	echo "symlink" "$@"
	local dst="$1" src="$2"
	src="$(readlink -f "$src")"
	[[ -L "$dst" && "$(readlink "$dst")" = "$src" ]] && return 0 # stop if dst is already a symlink to src
	[[ -L "$dst" && ! -e "$dst" ]] && rm "$dst" # continue if dst is a broken symlink
	[[ -e "$dst" ]] && { echo "error: dst exists" >&2; return 1 } # stop if dst exists
	mkdir -p "$(dirname "$dst")"
	ln -s "$src" "$dst"
}

function brewfile() {
	echo "brewfile" "$@"
	local src="$1"
	brew bundle check --no-upgrade --file "$src" > /dev/null && return 0 # stop if src is already installed
	brew bundle install --quiet --file "$src"
}

main "$@"
