#!/usr/bin/env zsh

set -e -o pipefail -u

function main() {
	local module_dir
	for module_dir in "$@"; do
		do_module "$module_dir"
	done
}

function do_module() {
	local module_dir="$1"

	[[ ! -e "$module_dir" ]] && return 0

	do_module_unhome "$module_dir" || echo "error" >&2
	do_module_home "$module_dir" || echo "error" >&2
	do_module_unbin "$module_dir" || echo "error" >&2
	do_module_bin "$module_dir" || echo "error" >&2
	do_module_unconfig "$module_dir" || echo "error" >&2
	do_module_config "$module_dir" || echo "error" >&2
	do_module_unintegration_zsh "$module_dir" || echo "error" >&2
	do_module_integration_zsh "$module_dir" || echo "error" >&2
	do_module_brewfile "$module_dir" || echo "error" >&2
}

function do_module_home() (
	local module_dir="$1"
	local remote_dir="$(get_home_dir)"
	local local_dir="$module_dir/.home"

	[[ ! -e "$local_dir" ]] && return 0

	local f
	for f in "$local_dir/"*(D); do
		symlink "$remote_dir/$(basename "$f")" "$f"
	done
)

function do_module_unhome() (
	local module_dir="$1"
	local remote_dir="$(get_home_dir)"
	local local_dir="$module_dir/.home"

	[[ ! -e "$remote_dir" ]] && return 0

	local f
	for f in "$remote_dir/"*(D); do
		unsymlink "$f" "$module_dir"
	done
)

function do_module_bin() (
	local module_dir="$1"
	local remote_dir="$(get_bin_dir)"
	local local_dir="$module_dir/.bin"

	[[ ! -e "$local_dir" ]] && return 0

	local f
	for f in "$local_dir/"*(D); do
		symlink "$remote_dir/$(basename "$f")" "$f"
	done
)

function do_module_unbin() (
	local module_dir="$1"
	local remote_dir="$(get_bin_dir)"
	local local_dir="$module_dir/.bin"

	[[ ! -e "$remote_dir" ]] && return 0

	local f
	for f in "$remote_dir/"*(D); do
		unsymlink "$f" "$module_dir"
	done
)

function do_module_config() (
	local module_dir="$1"
	local remote_dir="$(get_config_dir)"
	local local_dir="$module_dir/.config"

	[[ ! -e "$local_dir" ]] && return 0

	local f
	for f in "$local_dir/"*(D); do
		symlink "$remote_dir/$(basename "$f")" "$f"
	done
)

function do_module_unconfig() (
	local module_dir="$1"
	local remote_dir="$(get_config_dir)"
	local local_dir="$module_dir/.config"

	[[ ! -e "$remote_dir" ]] && return 0

	local f
	for f in "$remote_dir/"*(D); do
		unsymlink "$f" "$module_dir"
	done
)

function do_module_integration_zsh() (
	local module_dir="$1"
	local remote_dir="$(get_integration_zsh_dir)"
	local local_dir="$module_dir/.integration/zsh"

	[[ ! -e "$local_dir" ]] && return 0

	local f
	for f in "$local_dir/"*(D); do
		symlink "$remote_dir/$(basename "$f")" "$f"
	done
)

function do_module_unintegration_zsh() (
	local module_dir="$1"
	local remote_dir="$(get_integration_zsh_dir)"
	local local_dir="$module_dir/.integration/zsh"

	[[ ! -e "$remote_dir" ]] && return 0

	local f
	for f in "$remote_dir/"*(D); do
		unsymlink "$f" "$module_dir"
	done
)

function do_module_brewfile() (
	local module_dir="$1"
	local local_file="$module_path/.brewfile"

	[[ ! -e "$local_file" ]] && return 0

	brewfile "$local_file"
)

function get_home_dir() {
	printf "%s" "$HOME"
}

function get_bin_dir() {
	printf "%s" "$HOME/.local/bin"
}

function get_config_dir() {
	printf "%s" "$HOME/.config"
}

function get_integration_zsh_dir() {
	printf "%s" "$HOME/.local/share/zsh/integration"
}

function symlink() {
	local dst="$1" src="$2"
	[[ "$(basename "$src")" = "." ]] && return 0 # stop if src is "."
	[[ "$(basename "$src")" = ".." ]] && return 0 # stop if src is ".."
	[[ "$(basename "$src")" = ".DS_Store" ]] && return 0 # stop if src is ".DS_Store"

	echo "symlink" "$@"
	src="$(readlink -f "$src")"
	[[ -L "$dst" && "$(readlink "$dst")" = "$src" ]] && return 0 # stop if dst is already a symlink to src
	[[ -L "$dst" && ! -e "$dst" ]] && rm "$dst" # continue if dst is a broken symlink
	[[ -e "$dst" ]] && { echo "error: dst exists" >&2; return 1 } # stop if dst exists
	mkdir -p "$(dirname "$dst")"
	ln -s "$src" "$dst"
}

function unsymlink() {
	local dst="$1" dir="$2"
	dir="$(readlink -f "$dir")"
	[[ "$(basename "$dst")" = "." ]] && return 0 # stop if src is "."
	[[ "$(basename "$dst")" = ".." ]] && return 0 # stop if src is ".."
	[[ "$(basename "$dst")" = ".DS_Store" ]] && return 0 # stop if src is ".DS_Store"
	[[ ! -L "$dst" ]] && return 0 # stop if dst is not a symlink
	[[ "$(readlink "$dst")" != "$dir/"* ]] && return 0 # stop if dst source is not in dir
	[[ -e "$dst" ]] && return 0 # stop if dst exists, meaning it is not broken

	echo "unsymlink" "$@"
	rm "$dst"
}

function brewfile() {
	echo "brewfile" "$@"
	local src="$1"
	brew bundle check --no-upgrade --file "$src" > /dev/null && return 0 # stop if src is already installed
	brew bundle install --quiet --file "$src"
}

main "$@"
