#!/usr/bin/env zsh

set -e -o pipefail -u

function main() {
	local dot_bin="$HOME/.local/bin/dot-v2"
	( cd ~/Repositories/@house/dotfiles/dot && go build -o "$dot_bin" . )
	"$dot_bin" "$@"
}

main "$@"
