Env = [
  ["FPATH", "$XDG_CONFIG_HOME/zsh/completions:$FPATH"],
  ["HISTFILE", "$XDG_DATA_HOME/zsh/.zhistory"],
  ["HISTSIZE", "10000"],
  ["KEYTIMEOUT", "1"],
  ["PROMPT_EOL_MARK", ""],
  ["PS2", "%B…%b "],
  ["SAVEHIST", "10000"],
  ["PROMPT_STYLE", "regular"],                          # user-defined
  ["ZCOMPDUMP", "$XDG_CACHE_HOME/zsh/.zcompdump"],      # user-defined
]

BrewFormula = [
  ["zsh"],
]

File = [
  ["$HOME/.zshenv", ".zshenv"],
  ["$XDG_CONFIG_HOME/zsh", "config"],
]
