BrewCask = [
  ["transmission"],
]

Default = [
  ["org.m0k.transmission", "CheckRemoveDownloading", true],   # don't ask before removing a non-downloading transfer
  ["org.m0k.transmission", "DeleteOriginalTorrent", true],    # trash original torrent files
  ["org.m0k.transmission", "DownloadAsk", false],             # don't ask before starting a download
  ["org.m0k.transmission", "DownloadLocationConstant", true], # download torrents to the ~/Downloads folder
  ["org.m0k.transmission", "MagnetOpenAsk", false],           # don't ask before opening a magnet link
  ["org.m0k.transmission", "RandomPort", true],               # randomize port on launch
  ["org.m0k.transmission", "WarningDonate", false],           # hide the donate message
  ["org.m0k.transmission", "WarningLegal", false],            # hide the legal disclaimer
]
