- brew-cask: ["hammerspoon"]
- file-link: ["$XDG_CONFIG_HOME/hammerspoon", "config"]
- default: ["org.hammerspoon.Hammerspoon", "MJConfigFile", "$XDG_CONFIG_HOME/hammerspoon/init.lua"] # follow XDG Base Directory, see https://github.com/Hammerspoon/hammerspoon/issues/2175
- default: ["org.hammerspoon.Hammerspoon", "MJShowDockIconKey", false]                              # hide the Dock icon
- default: ["org.hammerspoon.Hammerspoon", "MJShowMenuIconKey", false]                              # hide the menu bar icon
